import { LatexDocument } from '@/types/document';

export const LABOUR_PO_TEMPLATE: LatexDocument = {
  id: 'labour_po',
  title: 'GLOBAL INDUSTRIES CIVIL LABOUR CONTRACT WORK ORDER',
  subtitle: 'GI/CIVIL/2026/101',
  authors: [
    {
      id: 'auth_1',
      name: 'GLOBAL INDUSTRIES',
      affiliation: 'Vadodara, Gujarat',
      email: 'info@globalindustries.co',
    },
    {
      id: 'auth_2',
      name: 'Mohammad Kamil Shaikh',
      affiliation: 'Labour Contractor',
      email: 'contact@contractor.in',
    },
  ],
  date: '05/08/2026',
  abstract: '',
  keywords: ['Civil Work', 'Labour Contract', 'Work Order', 'Global Industries'],
  settings: {
    paperSize: 'a4paper',
    fontSize: '10pt',
    columns: 'onecolumn',
    fontFamily: 'helvetica',
    margins: 'compact',
    showPageNumbers: false,
    showDate: false,
    accentColor: '#505050',
  },
  purchaseOrder: {
    companyName: 'GLOBAL',
    companySubtitle: 'INDUSTRIES',
    companyAddress: [
      'SO7B / 2nd Floor / Phase 2',
      'Indiabulls, Jetalpur Road',
      'Vadodara',
    ],
    gstNo: '24CLNPS9550H1ZI',
    companyPhone: '+91 97254 45370',
    companyAddressFooter: 'Block No. 1068/99, Ratnakar Business Hub, Por GIDC, Ramangamdi Road, Vadodara - 391243',
    companyEmail: 'info@globalindustries.co',
    companyWebsite: 'www.globalindustries.co',
    leftServices: [
      '• Pre Engineering Building',
      '• Roofing Solution',
      '• Engineering Project & Designing',
      '• "Z" & "C" Purlins',
      '• UPVC Roofing Sheet',
    ],
    rightServices: [
      '• Infra Materials',
      '• Puf Panels & Insulation Roofing',
      '• Skylight Sheets',
      '• Air Ventilators',
    ],
    contractorName: 'Mohammad Kamil Shaikh',
    projectName: 'Civil Construction Work',
    projectLocation: 'Sevasi TP-1, Vadodara, Gujarat',
    poNumber: 'GI/CIVIL/2026/101',
    poDate: '05/08/2026',
    scopeOfWork: [
      'Site cleaning and layout assistance',
      'Excavation and backfilling',
      'PCC work',
      'RCC Footing',
      'RCC Pedestal',
      'RCC Column',
      'RCC Beam',
      'Reinforcement Binding',
      'Centering & Shuttering',
      'Concrete Pouring, Vibrating & Curing',
      'Brick/Block Masonry',
      'Internal & External Plaster',
      'PCC Flooring & Finishing',
      'Trimix Flooring / Concrete Work, including compaction, metal, quarry dust and concrete work',
      'Miscellaneous Civil Works',
      'Final Site Cleaning and Handing Over',
    ],
    rateItems: [
      {
        id: 'rate_1',
        description:
          'Complete Civil Labour Contract (Lumpsum/Uchak) including supervision, skilled and unskilled manpower, tools & tackles, centering/shuttering materials, scaffolding, machinery, equipment, transportation, curing, and safety equipment.',
        unit: 'Lumpsum',
        qty: '1 Job',
        rate: '4,70,000/-',
        total: '470000.00',
      },
    ],
    amountInWords: 'Rupees Four Lakh Seventy Thousand Only',
    scopeOfContractor: [
      '1. Contract Value: The total contract value is ₹4,70,000/- (Rupees Four Lakh Seventy Thousand Only) on a Lumpsum (Uchak) Labour Contract Basis. The contract value includes complete labour charges, supervision, skilled and unskilled manpower, tools & tackles, centering/shuttering materials, scaffolding, machinery, equipment, transportation, curing, safety equipment and all incidental expenses required for successful completion of the work. No extra payment shall be made unless specifically approved in writing by Global Industries.',
      '2. Scope of Work: The contractor shall execute complete civil labour work, including site cleaning, excavation, PCC, RCC Footing, Pedestal, Column, Beam, Reinforcement, Centering, Concrete Pouring, Masonry, Plaster, Flooring, and Finishing strictly as per approved drawings, specifications and Site Engineer instructions.',
      '3. Company Scope: Global Industries shall supply only construction materials including Cement, Steel, Sand, Aggregate, Bricks/Blocks, RMC/Concrete, and Water.',
      '4. Contractor Scope: The contractor shall arrange at his own cost Skilled, Semi-Skilled & Unskilled Labour, Masons, Carpenters, Bar Benders, Site Supervisor, Centering/Shuttering Material, Scaffolding, Tools & Tackles, Concrete Vibrator, Cutting Machine, PPE, Accommodation, Transportation, Food & Water, Housekeeping, and Electricity.',
    ],
    paymentTerms: [
      'Footing Work Completion: ₹50,000/-',
      'RCC Beam Work: ₹20,000/-',
      'Plinth Completion: ₹50,000/-',
      'Masonry & RCC Work Completion: ₹1,00,000/-',
      'Plaster Work Completion: ₹80,000/-',
      'Floor Concrete Work Completion: ₹1,20,000/-',
      'After Final Completion: ₹50,000/-',
      'All payments shall be released after verification and certification of the respective stage by the Site Engineer. Applicable TDS shall be deducted as per Government Rules.',
    ],
    measurementClause: [
      '5. Quality: The contractor shall execute all works strictly as per approved drawings, specifications and Site Engineer instructions. Any defective, rejected or poor-quality work shall be dismantled and re-executed by the contractor at his own cost without any additional payment.',
      '6. Material Responsibility: All materials supplied by Global Industries shall remain the sole property of the Company. The contractor shall ensure proper handling, storage and usage. Any loss, theft, damage or excessive wastage due to negligence shall be recovered from the contractor\'s bills.',
      '7. Safety: The contractor shall strictly comply with all applicable safety rules and regulations. All workers shall wear proper PPE while working. The contractor shall be solely responsible for any accident, injury, death or property damage arising due to negligence or violation of safety norms.',
    ],
    termsAndConditions: [
      '8. Labour Laws: The contractor shall comply with all applicable labour laws including Minimum Wages Act, Labour License, PF, ESIC, Workmen Compensation Insurance, and BOCW Act. All labour disputes shall be the sole responsibility of the contractor.',
      '9. Measurement & Payment: Payments are released upon stage certification by the Site Engineer. GST paid only against valid GST invoice. Recoveries for defective work/wastage apply.',
      '10. Time Schedule: Completion within 60 (Sixty) days from commencement. Penalty of ₹2,000/- per day for delay.',
    ],
    page3Terms: [
      '11. Housekeeping: Maintain work area clean throughout execution and remove debris regularly.',
      '12. Warranty / Defect Liability: Rectify workmanship defects observed during execution or within 6 months from completion without additional payment.',
      '13. Variation / Extra Work: Extra work requires prior written approval from Global Industries. Verbal instructions not considered.',
      '14. Termination: Global Industries reserves the right to terminate without prior notice in case of poor workmanship, delay, safety violations, labour shortage, or breach of terms.',
      '15. Force Majeure: Neither party responsible for delay caused due to natural calamities, Government restrictions, war, flood, earthquake.',
      '16. Jurisdiction: Subject to exclusive jurisdiction of competent courts at Vadodara, Gujarat only.',
    ],
    signatoryCompany: 'For GLOBAL INDUSTRIES\nAuthorized Signatory',
    signatoryContractor: 'Accepted By Contractor\nName & Signature',
  },
  sections: [],
  equations: [],
  figures: [],
  tables: [],
  references: [],
};


export const BLANK_TEMPLATE: LatexDocument = {
  id: 'blank',
  title: 'Untitled Document',
  subtitle: '',
  authors: [
    {
      id: 'auth_1',
      name: 'Author Name',
      affiliation: 'Organization',
      email: 'author@domain.com',
    },
  ],
  date: 'August 14, 2026',
  abstract: '',
  keywords: [],
  sections: [
    {
      id: 'sec_1',
      title: 'Introduction',
      subsections: [
        {
          id: 'sub_1',
          title: 'Overview',
          contentType: 'paragraph',
          body: 'Start typing your LaTeX document content here.',
        },
      ],
    },
  ],
  equations: [],
  figures: [],
  tables: [],
  references: [],
  settings: {
    paperSize: 'a4paper',
    fontSize: '11pt',
    columns: 'onecolumn',
    fontFamily: 'times',
    margins: 'normal',
    showPageNumbers: true,
    showDate: true,
    accentColor: '#1e3a8a',
  },
};

export const TAX_INVOICE_TEMPLATE: LatexDocument = {
  id: 'tax_invoice',
  title: 'TAX-INVOICE - ALEMBIC LTD',
  subtitle: 'TI/26-27/00013',
  authors: [
    {
      id: 'auth_inv1',
      name: 'GLOBAL INDUSTRIES',
      affiliation: 'Vadodara, Gujarat',
      email: 'info@globalindustries.co',
    },
    {
      id: 'auth_inv2',
      name: 'M/s. ALEMBIC LTD',
      affiliation: 'Alembic Road, Gorwa, Vadodara',
      email: 'contact@alembic.com',
    },
  ],
  date: '19/08/2026',
  abstract: '',
  keywords: ['Tax Invoice', 'GST', 'Global Industries', 'Alembic Ltd'],
  settings: {
    paperSize: 'a4paper',
    fontSize: '10pt',
    columns: 'onecolumn',
    fontFamily: 'helvetica',
    margins: 'compact',
    showPageNumbers: false,
    showDate: false,
    accentColor: '#1e3a8a',
  },
  taxInvoice: {
    companyName: 'GLOBAL',
    companySubtitle: 'INDUSTRIES',
    companyGstNo: '24CLNPS9550H1ZI',
    companyPanNo: 'CLNPS9550H',
    companyEpfNo: 'VDBRD18741500',
    companyPhone: '+91 97254 45370',
    companyAddressHeader: 'Regd. Off. : SO7B / 2nd floor, Ratnakar Business Hub, Por GIDC, Ramangamdi Road, Vadodara, Gujarat - 391243',
    companyAddressFooter: 'Block No. 1068/99, Ratnakar Business Hub, Por GIDC, Ramangamdi Road, Vadodara - 391243',
    companyEmail: 'info@globalindustries.co',
    companyWebsite: 'www.globalindustries.co',
    leftServices: [
      '• Pre Engineering Building',
      '• Roofing Solution',
      '• Engineering Project & Designing',
      '• "Z" & "C" Purlins',
    ],
    rightServices: [
      '• Infra Materials',
      '• Puf Panels & Insulation Roofing',
      '• Skylight Sheets',
      '• Air Ventilators',
    ],
    clientName: 'M/s. ALEMBIC LTD,',
    clientAddressLine1: 'Alembic Road, Gorwa,',
    clientAddressLine2: 'Vadodara. Gujarat',
    clientGstNo: '24AABCA7950P1ZB',
    invoiceNo: 'TI/26-27/00013',
    invoiceDate: '19/08/2026',
    poNo: '1300000567',
    poDate: '08/06/2026',
    projectName: 'Tadpole Academy',
    items: [
      {
        id: 'inv_item_1',
        srNo: '1.',
        description: '65% -- Material Supply, Fabrication, Erection & Primer Painting Work Completed.',
        hsn: '73089010',
        qty: '5041.264',
        rate: '79.3',
        total: '399772.23',
      },
    ],
    totalAmount: '399772.23',
    sgstRate: '9%',
    sgstAmount: '35979.50',
    cgstRate: '9%',
    cgstAmount: '35979.50',
    netAmount: '471731.24',
    amountInWords: 'Rupee: Four Lakhs Seventy-One Thousand Seven Hundred Thirty-One Only.',
    finalAmount: '471731.00',
    termsLines: [
      '1. GOODS ONCE SOLD WILL NOT BE TAKEN BACK.',
      '2. PAYMENT SHOULD BE MADE AS PER TERMS.',
      '3. SUBECT TO BE VADODARA JURISDICATION ONLY.',
    ],
    bankDetails: {
      bankName: 'BANK OF BARODA',
      ifsc: 'BARB0INDMAK',
      accountNo: '05730400000392',
      branch: 'MAKARPURA GIDC.',
    },
    signatoryCompany: 'For, GLOBAL INDUSTRIES',
  },
  sections: [],
  equations: [],
  figures: [],
  tables: [],
  references: [],
};

export const QUOTATION_TEMPLATE: LatexDocument = {
  id: 'quotation',
  title: 'QUOTATION - Construction of Round Roof System (Trussless Roof)',
  subtitle: 'GI-PRE-FAB-EQ-0786/1002',
  authors: [
    {
      id: 'auth_1',
      name: 'GLOBAL INDUSTRIES',
      affiliation: 'Vadodara, Gujarat',
      email: 'info@globalindustries.co',
    },
    {
      id: 'auth_2',
      name: 'Mr. Apurvabhai Patel',
      affiliation: 'Client',
      email: 'client@example.com',
    },
  ],
  date: '27/03/2026',
  abstract: 'Quotation for Construction of Round Roof System (Trussless Roof), Civil and Structural Steel Erection.',
  keywords: ['Quotation', 'Round Roof', 'Trussless Roof', 'Pre-Engineered Building', 'Civil Work'],
  settings: {
    paperSize: 'a4paper',
    fontSize: '10pt',
    columns: 'onecolumn',
    fontFamily: 'helvetica',
    margins: 'compact',
    showPageNumbers: false,
    showDate: false,
    accentColor: '#1e3a8a',
  },
  quotation: {
    companyName: 'GLOBAL',
    companySubtitle: 'INDUSTRIES',
    companyGstNo: '24CLNPS9550H1ZI',
    companyPhone: '+91 97254 45370',
    companyAddressHeader: 'Regd. Off. : SO7B / 2nd floor, Ratnakar Business Hub, Por GIDC, Ramangamdi Road, Vadodara, Gujarat - 391243',
    companyAddressFooter: 'Block No. 1068/99, Ratnakar Business Hub, Por GIDC, Ramangamdi Road, Vadodara - 391243',
    companyEmail: 'info@globalindustries.co',
    companyWebsite: 'www.globalindustries.co',
    leftServices: [
      '• Pre Engineering Building',
      '• Roofing Solution',
      '• Engineering Project & Designing',
      '• "Z" & "C" Purlins',
      '• UPVC Roofing Sheet',
    ],
    rightServices: [
      '• Infra Materials',
      '• Puf Panels & Insulation Roofing',
      '• Skylight Sheets',
      '• Air Ventilators',
    ],

    // Page 1: Cover & Greeting
    toRecipient: 'Mr. Apurvabhai Patel',
    toAddress: 'Vadodara, gujrat',
    refNo: 'GI-PRE-FAB-EQ-0786/1002',
    date: '27/03/2026',
    subjectTitle: 'Quotation for Construction of Round Roof System (Trussless Roof)',
    introParagraphs: [
      'With reference to your Valued Enquiry, we hereby submit our Technical Offer as under.',
      'We thank you for giving us the opportunity to submit our proposal for the above-mentioned project.',
      'Our scope of work covers the design, fabrication, Civil, supply and erection of materials in accordance with the enclosed standards and specifications of M/S. Global Industries Metal Building system, unless otherwise stated.',
      'This proposal is indexed for easy reference and includes scope of supply, building description and design loads/criteria, standard product specifications and standard conditions of sale.',
      'We assure you of our best attention and services and look forward to your favorable response at the earliest.',
    ],
    signatoryName: 'Global Industries',
    signatoryPhones: ['09725445370', '09725865370'],

    // Page 2: Technical Details
    technicalDetails: [
      { label: 'Building Area', value: '8775.00 SQFT' },
      { label: 'Width(m)', value: '20 MTR' },
      { label: 'Length(m)', value: '41 MTR' },
      { label: 'Eave ht.(m)', value: '25 Ft Clear Height' },
      { label: 'Width module(m)', value: 'Clear Span Building' },
      { label: 'Bay Spacing Side wall', value: '3 MT.' },
      { label: 'Round Roof Panels', value: '1 mm thk color coated roof sheet' },
      { label: 'Side wall', value: '10 Foot wall' },
      { label: 'RCC WORK', value: '4" INCH' },
      { label: 'Daylight Sheet', value: 'N.A' },
      { label: 'Canopy', value: 'N.A' },
      { label: 'Framed Opening', value: 'DOOR 2 NOS' },
      { label: 'Wet mix', value: '5" inch' },
      { label: 'Footing Nos.', value: 'As per Drwings' },
      { label: 'COLUMN SIZE', value: 'As per Drwings' },
      { label: 'STEEL MAKE', value: 'SAIL/JINDAL/ASIAN/APL/ESSAR/AMNS' },
    ],

    // Page 3: Material Specifications
    specifications: [
      {
        title: 'TMT Steel Bar Specification',
        details: 'Grade: Fe-500/Fe-500D/Fe-550 (as per client requirement) \nStandard: IS 1786:2008 compliant \nType: Thermo-Mechanically Treated (TMT) Rebars \nDiameter Range: 8 mm, 10 mm, 12 mm, 16 mm, 20 mm, 25 mm \nYield Strength: As per grade selected \nRib Pattern: Continuous CNC-rolled ribs for superior bonding with concrete \nElongation: Higher ductility for better seismic & bending performance \nCorrosion Resistance: Low carbon content and controlled chemistry \nUsage: Suitable for footing, column, beam, slab & all RCC works',
      },
      {
        title: 'foundation works \n Cement Specification',
        details: 'For the foundation works, we will use OPC (Ordinary Portland Cement) to ensure maximum strength and durability.',
      },
      {
        title: 'Chhantar (slab work) and \n Plastering \n Cement Specification',
        details: 'We will use PPC (Portland Pozzolana Cement) as it provides better finish, workability, and long-term performance for these applications.',
      },
      {
        title: 'Self-Drilling Screws Specification',
        details: 'Self-drilling roofing fasteners \nSize: 12 $\\times$ 55 mm / 12 $\\times$ 50 mm (as per sheet profile & purlin thickness) \nMaterial: High-tensile carbon steel \nCoating: Ruspert/Zinc Coating for corrosion resistance \nWasher: Hex head with EPDM sealing washer \nHead Type: Hexagonal head (5/16") \nDrill Point: No. 5 / No. 3 self-drill point \nApplication: Suitable for fixing roofing and cladding sheets \nStandard: As per AS3566 / equivalent quality standard',
      },
    ],

    // Page 4: Commercial BOQ & Payment Terms
    commercialSubtitle: 'For PRE-FAB BUILDING',
    commercialItems: [
      {
        description: 'Execution of Works Contract for Self Supporting Roof SAC: 9954 Bay1-: \n(a) Span: 20 mtrs \n(b) Arch Rise: 4.57 mtrs \n(c) Length: 41 mtrs \n(d) Arch Length: 24.57 mtrs \n(e) No of Bays: 1 No. \n(f) Area Per Bay: 952.00 SQM \n(g) Height: 9.15 mtrs \nMaterial Specification: COLOUR COATED GALVALUME BMT: 1.10 mm APT: 1.15 mm Tolerance: +/-0.02 MM Coil Width: 912 mm Tolerance: +/- 4 mm \nTotal Round Roof sq ft. 10243/- sqft. X 235 \n8559/- kgs approx \nSteel column and Purlin Fabrication supply approx 15000 \nSteel column eriction work 13000 kgs. \nRoofing sheet jsw make 600 SQM \nRoofing sheet Fixing charges 600 SQM \nAir Bubble Insulation 8mm sheet 600 SQM',
        price: '24,07,227.20',
      },
      {
        description: 'FABRICATION WORK 6000X150',
        price: '900,000.00',
      },
      {
        description: 'Civil work.00 Sqft. 8823.2X 850/- Rate',
        price: '74,99,550.00',
      },
    ],
    totalPriceInInr: '10806777.20',
    subTotal: '10806777.00',
    amountInWords: 'Total: One Crore Eight Lakh Six Thousand Seven Hundred Seventy-Seven Only.',
    gstNote: '18% Gst Extra',
    paymentTermsFab: [
      '25% advance along with your confirmed order in favor of GLOBAL INDUSTRIES.',
      '75% against PI prior to material dispatch and machine planning.',
      'Payments to be issued to us by way of Pay-order/DD/at par Cheque favoring GLOBAL INDUSTRIES.',
      'All payments received by us will be forfeited in case of cancellation of order.',
    ],
    paymentTermsCivil: [
      '25% Advance with Purchase Order.',
      '30% at the time of Footing Casting.',
      '25% at the time of Brick wall work',
      '20% at the time of Flooring',
    ],

    // Page 5: Delivery Schedule
    deliverySchedule: [
      'Material will be delivered to your site within 10 to 12 weeks from the date we receive your techno commercially clear purchase-order, subject to your adherence to the agreed payment schedule.',
      'The machinery and manpower will be mobilized to your site within 2 weeks from the date of complete site-readiness, as confirmed by you and certificate by our engineer.',
      'We shall jointly review the site-progress at regular intervals. Any changes in the site handover schedule would obviously result in an extension of our delivery dates and hence delivery would be re-scheduled after mutual discussions.',
      'Any idling of our machine & crane due to non readiness of site shall be charged at Rs.20,000 for 8 hours.',
    ],

    // Page 6 & 7: Approved Vendor List & Notes
    vendorList: [
      { srNo: '1', description: 'Steel Plates', brand: 'Essar Steel (Arcelor Mittal Nippon) / JSW Steel / TATA Steel' },
      { srNo: '2', description: 'Bare & PPGL- Panel', brand: 'JSW / Tata BSL Steel' },
      { srNo: '3', description: 'Bare & PPGL- Panel', brand: '--' },
      { srNo: '4', description: 'GI Coil (for Purlin)', brand: 'Essar Steel (Arcelor Mittal Nippon) / JSW / Apollo / Good luck india' },
      { srNo: '5', description: 'HR Coil (for Purlin)', brand: 'Essar Steel (Arcelor Mittal Nippon) / JSW / Tata Steel' },
      { srNo: '6', description: 'Deck Sheeting', brand: 'JSW / Essar Steel (Arcelor Mittal Nippon)' },
      { srNo: '7', description: 'Hot Rolled Items', brand: 'Angle, Channel & Round Bar: - Ambica / Khandelwal steel / Shree Balram Industries / Varsana \nISMB: - Vandana / Topworth / Sujana / SKS Ispat / Varsana \nUB/UC: - JSPL \nCHS/SHS/RHS: - Riddhi Steel / Asian / Apollo / Surya' },
      { srNo: '8', description: 'Paint', brand: 'Hempel / Asian / Berger / Asian Sigma / Chroma / Akzonobel Paint / Omkar industries' },
      { srNo: '9', description: 'GI Sheet', brand: 'Essar Steel (Arcelor Mittal Nippon) / JSW / Asian' },
      { srNo: '10', description: 'Stitch Screw / SDTS', brand: 'Corro-shield / Real Fastner' },
      { srNo: '11', description: 'Fasteners Gr 8.8/4.6', brand: 'Pooja Forge / Karamtara / Deepak Fasteners / KM Fastner' },
      { srNo: '12', description: '2mm Polycarbonate (0.472m strip) for SSR', brand: "Tuflite / Skylight -- with 10 years supplier's standard warranty" },
      { srNo: '13', description: '2mm Polycarbonate (1m wide)', brand: "Tuflite / skylight -- with 10 years supplier's standard warranty" },
      { srNo: '14', description: '2mm FRP (1m wide)', brand: 'Ashapura Fiber Glass / US Fiber' },
      { srNo: '15', description: 'Turbo vents (Ø 600 mm)', brand: 'Sudha Ventilating System / Global Ind' },
      { srNo: '16', description: 'Ridge Vent (Ø 300/600 mm)', brand: 'Global Design' },
      { srNo: '17', description: 'Insulations (fiber glass)', brand: 'UP Twiga Fiberglass / Owens Corning / Aerolam' },
      { srNo: '18', description: 'Air Bubble Insulation / Foam Insulation', brand: 'Aerolam / Alutix / Divine / Supreme' },
      { srNo: '19', description: 'Rockwool Insulation', brand: 'Rockwool Insulation / Poly Bond / Roxul India' },
      { srNo: '20', description: 'Sandwich Panel Puff/PIR', brand: 'Kingspan (Jindal Mactec) / Rinac / Sintex / BNAL / Metecno / ISO therm' },
      { srNo: '21', description: 'Sealants / Rolls', brand: 'Sealant Tube -- Anabond / Mastic Roll -- Anabond' },
      { srNo: '22', description: 'Handrail (MS)', brand: 'Global design' },
      { srNo: '23', description: 'Welding Consumables', brand: 'Ador / Lincoln / Esab / Kiswel / HD' },
      { srNo: '24', description: 'Life Line', brand: 'MT & T / Karam / Standard with GI Rope & Post' },
      { srNo: '25', description: 'PVC -- Grey', brand: 'Dutron / Astral / Prince / FINOLEX / RAJ INDUSTRIES in Grey Color (any other Color / Make shall attract extra cost).' },
    ],
    taxNote: 'GST @ 18% Extra on above rate as mentioned in above table. However, any change in above tax structure will be paid extra to us, and vice-versa, during the time of actual invoicing.',
    notes: [
      'The above area mentioned is approx. only; however the final invoice will be made as per actual dimensions of the laid roof, i.e., curved roof with measurements jointly taken from the hem-top end of the panels.',
      'Above rates are inclusive of Required Quantity of Material and Consumables for the project. Any excess quantity of material & consumables/wastage at site is property of the Proflex Systems, and will be taken back by Proflex on completion of the project.',
      'Material transportation charges are Extra on above rate. Transit insurance for material, from Ahmedabad to your site is inclusive in the price.',
      'Unloading of the material at your site is Extra and to be arranged by CLIENT.',
      'If gutter is not available then scaffolding will be required during Roof installation and it will be in client scope.',
      'In case of higher capacity crane required for installation then it will be in scope of client.',
    ],
    deliveryChecklist: [
      'Submission of General Arrangement Drawings for approvals (as per our offered schedule)',
      'Acknowledgement of PO / Contract Agreement.',
      'Signed Contract Copy.',
      'Advance Payment as per terms, whichever is the Later.',
    ],
    deliveryNotes: 'Approved Drawings must be returned to M/s. Global industries, Vadodara within one week from submission of General Arrangement Drawings.\n\nThe change in General Arrangement Drawings needing redesign and or detailing changes shall result in time resource. However, the timeline shall be communicated during approval process by evaluating the nature of change basing building complexity.',

    // Page 8, 9, 10: Commercial Terms, Exclusions, Special Notes
    commercialTerms: [
      {
        number: 1,
        title: 'PROPOSAL VALIDITY:',
        content: 'This proposal is valid for (7) Seven Days from the date of this proposal. Any extension of the validity must be received in writing from M/s. Global Industries.',
      },
      {
        number: 2,
        title: 'CONTRACT VALIDITY:',
        content: 'A project where no progress is seen in terms of approval of drawing, approval of sheeting color, approval of sheeting pattern and unable to meet the agreed upon commercial terms for more than 2 months from the date of signing of the contract, could be subjected to price revision. If the project is cancelled, then the Cancellation policy shall be applicable.',
      },
      {
        number: 3,
        title: 'SPECIFICATION CHANGES:',
        content: "Seller reserve the right to modify the design of his standard buildings and to substitute material equal to or superior to that originally specified (to permit incorporation of changes and improvements, in the continued development of the Seller's product). \nIf any modification is made by the Buyer after giving drawing approval, the same shall have time and cost implication which would be borne by the Buyer. In such a case, a new purchase order/contract (incorporating the revised order value) shall be given to the Seller before which the seller is in no obligation to commence any project related activities.",
      },
      {
        number: 4,
        title: 'CANCELLATION:',
        content: 'Agreement and orders cannot be cancelled or modified by Buyer under any circumstances without Buyer first reaching an agreement in writing with Seller covering all damages. \nIf the buyer cancels the order, then the Buyer shall be subjected to order cancellation charges as hereunder:',
        subItems: [
          "10% of the total order value, if the production hasn't started and would be considered as engineering cost OR",
          '10% of the total order value plus the cost of material procured and or manufactured (based on tonnage) till the date of intimidation to the Seller in writing by the Buyer.',
        ],
        note: 'Buyer shall have the right to all the manufactured material, for which Buyer has paid to Seller.',
      },
      {
        number: 5,
        title: 'RELEASE FOR PRODUCTION:',
        content: 'That portion of this order that is not released for production within TWO Months from the date of Contract / Purchase Order that is not released for production for the reasons from buyer (hold / change in specifications etc.), might be subject to a price increase above noted time period.',
      },
      {
        number: 6,
        title: 'SHIPMENT:',
        content: 'Material of 1\\textsuperscript{st} Lot, that is shipped within 40 Days from date of Contract / Purchase Order could be subject to a price increase in accordance with Current Market prices (Material + Labor + 15\\% profit & overhead) posted at the end of the above noted period unless a longer delivery period is mutually agreed by Seller and Buyer. Unloading at jobsite is the responsibility of the Buyer / Builder.',
      },
      {
        number: 7,
        title: 'PAYMENT:',
        content: 'Any overdue payment shall attract Interest 0.3% per week on a compound interest basis and shall be levied on to the Buyer.',
      },
      {
        number: 8,
        title: 'CHARGES:',
        content: "All bank charges pertaining to LC shall be borne by the Buyer except charges of Seller's Bank. The seller's bank charges shall be borne by the seller.",
      },
      {
        number: 9,
        title: 'VARIATION ORDERS:',
        content: 'Lumpsum Order: Any change and / or revision to the above stated scope of supply shall lead to a variation in the price and the delivery period which shall be communicated to the buyer basing the nature of change/revision. \nBOQ Order: Any change and or revision if in a BOQ shall leads to variation in the price & the delivery period if each item decreases by 25\\% in Qty & Overall contract value decreases by 2.5\\% then the revised rates shall be communicated.',
      },
      {
        number: 10,
        title: 'FORCE MAJEURE:',
        content: "SELLER shall not be liable for any loss or damage to Buyer for delay in delivery or cancellation of any Purchaser's Orders by Seller due to circumstances beyond Seller's control, such as, but not limited to, war, riots, civil commotion, revolution, government regulations, orders, or acts of any government authority directly or indirectly interfering with or rendering more burdensome the production or delivery of the products, floods, fires, delays due to transporter's strike and any other circumstance or event beyond Seller's control.",
      },
      {
        number: 11,
        title: 'PERMITS:',
        content: 'DCC: Client should give Delivery Clearance Certificate on time to achieve the timeline / completion of project. The delay in DCC shall be considered for timeline extensions. \nRoad Permits: Buyer shall be responsible or liable to provide necessary permits on time to the Seller for transport (Road permits), erect or install any product. Any delays arising shall be to the account of the buyer.',
      },
      {
        number: 12,
        title: 'INSPECTION OF PRODUCT:',
        content: "Raw Material Inspection: Buyer agrees to inspect upon arrival of all articles shipped. Claims for shortages or defective material, if not packaged, must be made in writing to the Seller's Local Sales Office within five days after receipt of the shipment, and if packaged within 30 days after receipt of shipment Seller shall have a reasonable time to investigate all claims made by Buyer. Any claims for shortages or defects made after the above periods shall be refused and finally dismissed. \nBefore Dispatch: Finished good material's, inspection should be done by Buyer or his representative or his Third Party on readiness of material but before dispatch.",
      },
      {
        number: 13,
        title: 'DELIVERY:',
        content: 'Within 16 to 18 Weeks from Approval of GA drawing.',
      },
      {
        number: 14,
        title: 'STRUCTURE STABILITY:',
        content: 'M/s. Global Industries shall offer structure stability certificate for its designed offering for a period of 20 years from the date of erection completion, the same shall be issued by M/s. Global Industries and shall be effective from the date of receipt of completion certificate and commercial clearances whichever is later.',
      },
      {
        number: 15,
        title: 'SCOPE OF AGREEMENT:',
        content: 'It is further understood that this Agreement is the only agreement express or implied, either verbal or in writing, in connection with this sale.',
      },
      {
        number: 16,
        title: 'GOVERNING LAWS:',
        content: 'This agreement shall be construed and enforced in accordance with and under the laws of the Government of India.',
      },
      {
        number: 17,
        title: 'ARBITRATION:',
        content: 'Both parties agree that in case of any difference or dispute arising between the Seller and the Buyer will be resolved by mutual discussions and agreement. However, unresolved issues, if any, will be settled by arbitration as per the latest Indian Arbitration and Conciliation Act, and the venue of the arbitration will be Vadodara.',
      },
    ],
    exclusions: [
      'Windows, Ladders, Glazing, etc.,',
      'Items quoted as optional have not been considered in Basic Building.',
      'The contract does not include any material in connection with foundations, concrete, grouting under columns or in recess around bottom of wall sheets, plumbing, finished painting, heating, masonry, interior finishing, partitions, glass and glazing or any item not shown in Approval Drawings, unless specifically mentioned in this Agreement.',
      'Any type of Civil & Electrical works.',
      "Anything other than mentioned in Global's offering.",
    ],
    specialNotes: [
      'We shall provide only internal materials test certificates instead of testing data submission.',
      'Anchor Bolt Drawings, General Arrangement Drawings and Design Calculations shall be provided.',
      "Global shall furnish Approval Drawings and Design Calculations if required and mutually agreed upon; Vetting shall be in client's Scope.",
      'Panel Configuration (Roof & Wall) and Screws Pattern shall be as per Standard Roof sheet.',
      'Packing material used for shipments of Building components shall be brought back by Global along with residual steel material left over post building completion but without any Credit Note.',
      'Non-shrink grouting below base plate is in the scope of client.',
    ],
    finalSignatoryCompany: 'For, GLOBAL INDUSTRIES',
    finalSignatoryTitle: '(Authorised Signatory)',
  },
  sections: [],
  equations: [],
  figures: [],
  tables: [],
  references: [],
};

export const SAMPLE_TEMPLATES: Record<string, LatexDocument> = {
  quotation: QUOTATION_TEMPLATE,
  tax_invoice: TAX_INVOICE_TEMPLATE,
  labour_po: LABOUR_PO_TEMPLATE,
  blank: BLANK_TEMPLATE,
};

export const LABOUR_PO_DATA = LABOUR_PO_TEMPLATE.purchaseOrder!;

